### ISSUE TITLE
ä (a umlaut) not imported correctly

### ISSUE THREAD

**Issue by mchendriks** [doy/spreadsheet-parsexlsx#53] opened 2016-02-10 10:32 UTC
Letters with umlauts are not converted correctly. Is this a setting or a configurable something?

**Comment by doy** [comment] 2016-05-22 06:36
What do you mean by "converted correctly"? As far as I can tell, letters with umlauts work properly. Do you have a specific example of a thing that doesn't work?

**Comment by doy** [comment] 2016-08-16 06:36
Closing, since I can't reproduce this issue. Feel free to reopen it (with an example that doesn't work) if you're still having problems.

**Closed by doy** 2016-08-16 06:36 UTC
