### ISSUE TITLE
Formatted value of field containing '1' is 'General'

### ISSUE THREAD

**Issue by Tux** [doy/spreadsheet-parsexlsx#54] opened 2016-03-22 19:47 UTC
```
bless ({
    Format           => bless ({
        AlignH           => 0,
        AlignV           => 2,
        BdrColor         => [
            undef,
            undef,
            undef,
            undef
            ],
        BdrDiag          => [
            0,
            0,
            undef
            ],
        BdrStyle         => [
            0,
            0,
            0,
            0
            ],
        Fill             => [
            0,
            undef,
            undef
            ],
        FmtIdx           => 164,
        Font             => bless ({
            Bold             => 0,
            Color            => '#000000',
            Height           => 11,
            Italic           => 0,
            Name             => 'Calibri',
            Strikeout        => 0,
            Super            => 0,
            Underline        => 0,
            UnderlineStyle   => 0
            }, 'Spreadsheet::ParseExcel::Font'),
        FontNo           => 0,
        Hidden           => 0,
        IgnoreAlignment  => 1,
        IgnoreBorder     => 1,
        IgnoreFill       => '',
        IgnoreFont       => 1,
        IgnoreNumberFormat => 1,
        IgnoreProtection => 1,
        Indent           => 0,
        Lock             => 1,
        Merged           => '',
        Rotate           => 0,
        Shrink           => 0,
        Wrap             => 0
        }, 'Spreadsheet::ParseExcel::Format'),
    FormatNo         => 1,
    Merged           => '',
    Type             => 'Numeric',
    Val              => 1,
    _Value           => 'General',        # WRONG
    }, 'Spreadsheet::ParseExcel::Cell' )
```
When saving the xlsx as xls and parsing with Spreadsheet::ParseExcel:
```
bless ({
    Code             => undef,
    Format           => bless ({
        AlignH           => 0,
        AlignV           => 2,
        BdrColor         => [
            0,
            0,
            0,
            0
            ],
        BdrDiag          => [
            0,
            0,
            0
            ],
        BdrStyle         => [
            0,
            0,
            0,
            0
            ],
        Fill             => [
            0,
            64,
            65
            ],
        FmtIdx           => 164,
        Font             => bless ({
            Attr             => 0,
            Bold             => 0,
            Color            => 8,
            Height           => 11,
            Italic           => 0,
            Name             => 'Calibri',
            Strikeout        => 0,
            Super            => 0,
            Underline        => 0,
            UnderlineStyle   => 0
            }, 'Spreadsheet::ParseExcel::Font'),
        FontNo           => 0,
        Hidden           => 0,
        Indent           => 0,
        JustLast         => 0,
        Key123           => 0,
        Lock             => 1,
        Merge            => 0,
        ReadDir          => 0,
        Rotate           => 0,
        Shrink           => 0,
        Style            => 0,
        Wrap             => 0
        }, 'Spreadsheet::ParseExcel::Format'),
    FormatNo         => 26,
    Type             => 'Numeric',
    Val              => 1,
    _Kind            => 'MulRK',
    _Value           => 1,               # CORRECT
    }, 'Spreadsheet::ParseExcel::Cell' )
```

**Comment by doy** [comment] 2016-05-22 06:09
I can't reproduce this - can you give me an example spreadsheet with this problem?

**Comment by doy** [comment] 2016-08-16 06:37
Closing since I can't reproduce this. Feel free to reopen (with an example) if you're still having this problem.

**Closed by doy** 2016-08-16 06:37 UTC
